# Generated by Django 3.1.3 on 2021-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210119_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='barbecue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('COMPARTIDA', 'COMPARTIDA'), ('SIN AIRE ACONDICIONADO', 'SIN AIRE ACONDICIONADO'), ('SEMI ACONDICIONADO', 'SEMI ACONDICIONADO'), ('AIRE ACONDICIONADO', 'AIRE ACONDICIONADO')], max_length=25),
        ),
    ]
