# Generated by Django 3.1.3 on 2021-01-19 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_auto_20210119_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('COMPARTIDA', 'COMPARTIDA'), ('SIN AIRE ACONDICIONADO', 'SIN AIRE ACONDICIONADO'), ('SEMI ACONDICIONADO', 'SEMI ACONDICIONADO'), ('AIRE ACONDICIONADO', 'AIRE ACONDICIONADO')], max_length=25)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('kitchen', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('barbecue', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Ingreso')),
                ('check_out', models.DateField(verbose_name='Egreso')),
                ('breakfast', models.BooleanField(default=True)),
                ('adults', models.IntegerField()),
                ('kids', models.IntegerField()),
                ('cars', models.IntegerField()),
                ('total', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
