# Generated by Django 3.1.3 on 2021-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210119_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('HOSTEL', 'HOSTEL'), ('SINAIR', 'SIN AIRE ACONDICIONADO'), ('SEMIAC', 'SEMI ACONDICIONADO'), ('AIREAC', 'AIRE ACONDICIONADO')], max_length=6),
        ),
    ]
