# Generated by Django 3.1.3 on 2021-01-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210120_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
    ]
