# Generated by Django 3.1.3 on 2021-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20210121_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('Saracura', 'Saracura'), ('Pa-caa', 'Pa-caa')], max_length=10),
        ),
    ]
