# Generated by Django 3.1.3 on 2021-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20210121_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kids',
        ),
    ]
